version: "3.7"

services:
  gizh_postgres_database:
    image: postgres
    container_name: gizh_postgres_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=gizh
      - POSTGRES_DB=gizh_postgress
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: gizh
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - gizh_postgres_database
    depends_on:
      - gizh_postgres_database


volumes:
  pgdata:
    driver: local
